# Generated by Django 5.2.4 on 2025-08-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_rename_description_trackinghistory_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackinghistory',
            old_name='current_balance',
            new_name='income',
        ),
        migrations.RemoveField(
            model_name='currentbalance',
            name='current_balance',
        ),
        migrations.AddField(
            model_name='currentbalance',
            name='income',
            field=models.FloatField(default=0.0),
        ),
    ]
