# Generated by Django 5.2.4 on 2025-08-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_rename_current_balance_trackinghistory_income_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentbalance',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
